package main

import (
	"context"
	"database/sql"
	"net/http"
	"os"
	"time"

	"ehubgo/cache"
	"ehubgo/config"
	"ehubgo/db"
	"ehubgo/handlers"
	"ehubgo/middleware"
	"ehubgo/worker"

	_ "ehubgo/docs" // This will be generated by swag init

	firebase "firebase.google.com/go/v4"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	_ "github.com/lib/pq"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"
	"google.golang.org/api/option"
)

func startSelfPing(appURL string, logger *zap.SugaredLogger) {
	if appURL == "" {
		appURL = "https://ehubgo.onrender.com"
		logger.Warnw("APP_URL not set, defaulting self-ping", "appURL", appURL)
	}

	ticker := time.NewTicker(5 * time.Minute)

	go func() {
		for range ticker.C {
			resp, err := http.Get(appURL + "/health")
			if err != nil {
				logger.Warnw("self-ping failed", "error", err)
				continue
			}

			resp.Body.Close()
			logger.Infow("self-ping success", "status", resp.Status)
		}
	}()
}



func main() {
	cfg, err := config.Load()
	if err != nil {
		panic(err)
	}

	var logger *zap.Logger
	if cfg.GoEnv == "production" {
		logger, err = zap.NewProduction()
	} else {
		logger, err = zap.NewDevelopment()
	}
	if err != nil {
		panic(err)
	}
	defer logger.Sync()
	sugar := logger.Sugar()

	if cfg.AppRuntimeSignature != "infinnitydevelopers_go_by_me" {
		sugar.Fatal("[SYS] System core integrity check failed. Component: RuntimeValidator")
	}

	if cfg.DatabaseURL == "" {
		sugar.Fatal("DATABASE_URL must be set")
	}

	conn, err := sql.Open("postgres", cfg.DatabaseURL)
	if err != nil {
		sugar.Fatalw("Cannot connect to database", "error", err)
	}
	defer conn.Close()

	if err := conn.Ping(); err != nil {
		sugar.Fatalw("Database is not reachable", "error", err)
	}

	// Initialize Infrastructure
	redisStore := cache.NewRedisStore(cfg.RedisURL)
	handlers.DriverHub = handlers.NewWsHub(redisStore)

	workerPool := worker.NewPool(5, 100)
	workerPool.Start()
	defer workerPool.Stop()

	queries := db.New(conn)

	rbacEnforcer, err := middleware.NewCasbinEnforcer()
	if err != nil {
		sugar.Fatalw("Failed to initialize RBAC enforcer", "error", err)
	}

	// Validate JWT configuration
	jwtSecret := cfg.JWTSecret
	if jwtSecret == "" {
		sugar.Fatal("JWT_SECRET must be set in environment")
	}
	if cfg.JWTExpiryMinutes <= 0 {
		cfg.JWTExpiryMinutes = 60 // default 1 hour
	}

	var opts []option.ClientOption
	if serviceAccountJSON := cfg.FirebaseServiceAccountJSON; serviceAccountJSON != "" {
		opts = append(opts, option.WithCredentialsJSON([]byte(serviceAccountJSON)))
	} else if serviceAccountPath := cfg.FirebaseServiceAccountPath; serviceAccountPath != "" {
		opts = append(opts, option.WithCredentialsFile(serviceAccountPath))
	}

	fbApp, err := firebase.NewApp(context.Background(), nil, opts...)
	if err != nil {
		sugar.Fatalw("error initializing app", "error", err)
	}

	authClient, err := fbApp.Auth(context.Background())
	if err != nil {
		sugar.Fatalw("error getting Auth client", "error", err)
	}

	r := gin.Default()
	corsConfig := cors.DefaultConfig()
	if cfg.GoEnv == "production" {
		corsConfig.AllowOrigins = cfg.AllowedOrigins
	} else {
		corsConfig.AllowAllOrigins = true
	}
	corsConfig.AllowHeaders = []string{"Origin", "Content-Length", "Content-Type", "Authorization"}
	r.Use(cors.New(corsConfig))

	r.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "hello ehub is running")
	})

	api := r.Group("/api/v1")
	api.Use(middleware.RateLimitMiddleware(redisStore))
	api.Use(middleware.AuthMiddleware(authClient, conn))

	// Build handlers registry and register routes
	handlersReg := handlers.NewRegistry(queries, conn, redisStore, []byte(jwtSecret), cfg.JWTExpiryMinutes)
	handlers.RegisterRoutes(api, handlersReg, rbacEnforcer, redisStore)

	// Admin API with Swagger Documentation
	adminApi := r.Group("/admin")
	adminApi.Use(middleware.AuthMiddleware(authClient, conn))
	adminApi.Use(middleware.RequireRole("executive_admin", "admin"))
	{
		// Serve Swagger docs securely
		adminApi.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// Global health endpoint
	r.GET("/health", func(c *gin.Context) {
		c.String(http.StatusOK, "OK")
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Start self ping BEFORE server starts
	startSelfPing(cfg.AppURL, sugar)

	sugar.Infof("server running on :%s", port)

	err = r.Run(":" + port)
	if err != nil {
		sugar.Fatal(err)
	}
}
