// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type BusinessVerificationStatus string

const (
	BusinessVerificationStatusPending            BusinessVerificationStatus = "pending"
	BusinessVerificationStatusUnderReview        BusinessVerificationStatus = "under_review"
	BusinessVerificationStatusDocumentsRequested BusinessVerificationStatus = "documents_requested"
	BusinessVerificationStatusDocumentVerified   BusinessVerificationStatus = "document_verified"
	BusinessVerificationStatusApproved           BusinessVerificationStatus = "approved"
	BusinessVerificationStatusRejected           BusinessVerificationStatus = "rejected"
	BusinessVerificationStatusSuspended          BusinessVerificationStatus = "suspended"
)

func (e *BusinessVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessVerificationStatus(s)
	case string:
		*e = BusinessVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessVerificationStatus: %T", src)
	}
	return nil
}

type NullBusinessVerificationStatus struct {
	BusinessVerificationStatus BusinessVerificationStatus `json:"business_verification_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if BusinessVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessVerificationStatus), nil
}

type ComplaintReason string

const (
	ComplaintReasonBadBehavior   ComplaintReason = "bad_behavior"
	ComplaintReasonNoShow        ComplaintReason = "no_show"
	ComplaintReasonUnsafeDriving ComplaintReason = "unsafe_driving"
	ComplaintReasonPaymentIssue  ComplaintReason = "payment_issue"
	ComplaintReasonOther         ComplaintReason = "other"
)

func (e *ComplaintReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ComplaintReason(s)
	case string:
		*e = ComplaintReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ComplaintReason: %T", src)
	}
	return nil
}

type NullComplaintReason struct {
	ComplaintReason ComplaintReason `json:"complaint_reason"`
	Valid           bool            `json:"valid"` // Valid is true if ComplaintReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullComplaintReason) Scan(value interface{}) error {
	if value == nil {
		ns.ComplaintReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ComplaintReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullComplaintReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ComplaintReason), nil
}

type DocumentType string

const (
	DocumentTypeIDProof         DocumentType = "id_proof"
	DocumentTypeBusinessLicense DocumentType = "business_license"
	DocumentTypeTaxCertificate  DocumentType = "tax_certificate"
	DocumentTypePermit          DocumentType = "permit"
	DocumentTypeOther           DocumentType = "other"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type PropertyTypeEnum string

const (
	PropertyTypeEnumApartment PropertyTypeEnum = "apartment"
	PropertyTypeEnumHouse     PropertyTypeEnum = "house"
	PropertyTypeEnumCondo     PropertyTypeEnum = "condo"
	PropertyTypeEnumVilla     PropertyTypeEnum = "villa"
	PropertyTypeEnumCabin     PropertyTypeEnum = "cabin"
	PropertyTypeEnumStudio    PropertyTypeEnum = "studio"
	PropertyTypeEnumTownhouse PropertyTypeEnum = "townhouse"
)

func (e *PropertyTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PropertyTypeEnum(s)
	case string:
		*e = PropertyTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PropertyTypeEnum: %T", src)
	}
	return nil
}

type NullPropertyTypeEnum struct {
	PropertyTypeEnum PropertyTypeEnum `json:"property_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if PropertyTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPropertyTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PropertyTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PropertyTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPropertyTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PropertyTypeEnum), nil
}

type UserRoleType string

const (
	UserRoleTypeExecutiveAdmin UserRoleType = "executive_admin"
	UserRoleTypeAdmin          UserRoleType = "admin"
	UserRoleTypeStaff          UserRoleType = "staff"
	UserRoleTypeVendor         UserRoleType = "vendor"
	UserRoleTypeCustomer       UserRoleType = "customer"
	UserRoleTypeDriver         UserRoleType = "driver"
	UserRoleTypeHost           UserRoleType = "host"
	UserRoleTypeC2cSeller      UserRoleType = "c2c_seller"
	UserRoleTypeStoreStaff     UserRoleType = "store_staff"
	UserRoleTypeUser           UserRoleType = "user"
)

func (e *UserRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleType(s)
	case string:
		*e = UserRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleType: %T", src)
	}
	return nil
}

type NullUserRoleType struct {
	UserRoleType UserRoleType `json:"user_role_type"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleType), nil
}

type Address struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	Label          sql.NullString `json:"label"`
	RecipientName  sql.NullString `json:"recipient_name"`
	RecipientPhone sql.NullString `json:"recipient_phone"`
	AddressLine1   string         `json:"address_line1"`
	AddressLine2   sql.NullString `json:"address_line2"`
	City           string         `json:"city"`
	State          sql.NullString `json:"state"`
	PostalCode     sql.NullString `json:"postal_code"`
	Country        string         `json:"country"`
	IsDefault      sql.NullBool   `json:"is_default"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type Appointment struct {
	ID              string         `json:"id"`
	PatientID       string         `json:"patient_id"`
	DoctorID        string         `json:"doctor_id"`
	AppointmentTime time.Time      `json:"appointment_time"`
	Status          sql.NullString `json:"status"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type B2bQuote struct {
	ID          string         `json:"id"`
	RfqID       string         `json:"rfq_id"`
	BusinessID  string         `json:"business_id"`
	TotalAmount string         `json:"total_amount"`
	Currency    string         `json:"currency"`
	ValidUntil  sql.NullTime   `json:"valid_until"`
	Status      string         `json:"status"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Bill struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	BillerName    string         `json:"biller_name"`
	AccountNumber string         `json:"account_number"`
	AmountDue     string         `json:"amount_due"`
	Currency      string         `json:"currency"`
	DueDate       sql.NullTime   `json:"due_date"`
	Status        sql.NullString `json:"status"`
	Category      sql.NullString `json:"category"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Brand struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	LogoUrl    sql.NullString `json:"logo_url"`
	CategoryID sql.NullString `json:"category_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type BusRoute struct {
	ID             string         `json:"id"`
	BusinessID     string         `json:"business_id"`
	Origin         string         `json:"origin"`
	Destination    string         `json:"destination"`
	DepartureTime  time.Time      `json:"departure_time"`
	ArrivalTime    sql.NullTime   `json:"arrival_time"`
	Price          string         `json:"price"`
	Currency       string         `json:"currency"`
	AvailableSeats int32          `json:"available_seats"`
	BusType        sql.NullString `json:"bus_type"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type Business struct {
	ID                 string                         `json:"id"`
	OwnerID            string                         `json:"owner_id"`
	Name               string                         `json:"name"`
	Description        sql.NullString                 `json:"description"`
	LogoUrl            sql.NullString                 `json:"logo_url"`
	BannerUrl          sql.NullString                 `json:"banner_url"`
	MiniserviceType    string                         `json:"miniservice_type"`
	AddressID          sql.NullString                 `json:"address_id"`
	PhoneNumber        sql.NullString                 `json:"phone_number"`
	Email              sql.NullString                 `json:"email"`
	IsActive           sql.NullBool                   `json:"is_active"`
	VerificationStatus NullBusinessVerificationStatus `json:"verification_status"`
	Rating             sql.NullString                 `json:"rating"`
	ReviewCount        sql.NullInt32                  `json:"review_count"`
	CreatedAt          sql.NullTime                   `json:"created_at"`
	UpdatedAt          sql.NullTime                   `json:"updated_at"`
}

type BusinessLocation struct {
	BusinessID string `json:"business_id"`
	AddressID  string `json:"address_id"`
}

type BusinessStaff struct {
	ID              string                `json:"id"`
	BusinessID      string                `json:"business_id"`
	UserID          string                `json:"user_id"`
	Role            string                `json:"role"`
	Permissions     pqtype.NullRawMessage `json:"permissions"`
	IsActive        sql.NullBool          `json:"is_active"`
	InvitedBy       sql.NullString        `json:"invited_by"`
	InvitationToken sql.NullString        `json:"invitation_token"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type BusinessVerificationLog struct {
	ID         string                         `json:"id"`
	BusinessID string                         `json:"business_id"`
	ActorID    string                         `json:"actor_id"`
	OldStatus  NullBusinessVerificationStatus `json:"old_status"`
	NewStatus  BusinessVerificationStatus     `json:"new_status"`
	Reason     sql.NullString                 `json:"reason"`
	CreatedAt  sql.NullTime                   `json:"created_at"`
}

type C2cListing struct {
	ID           string         `json:"id"`
	SellerID     string         `json:"seller_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	Price        string         `json:"price"`
	Currency     string         `json:"currency"`
	ImageUrls    []string       `json:"image_urls"`
	IsNegotiable sql.NullBool   `json:"is_negotiable"`
	Location     sql.NullString `json:"location"`
	Condition    sql.NullString `json:"condition"`
	Status       string         `json:"status"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type C2cSeller struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Bio       sql.NullString `json:"bio"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type CartItem struct {
	ID         string       `json:"id"`
	UserID     string       `json:"user_id"`
	BusinessID string       `json:"business_id"`
	ItemID     string       `json:"item_id"`
	ItemType   string       `json:"item_type"`
	Quantity   int32        `json:"quantity"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
}

type CasbinRule struct {
	ID    int32          `json:"id"`
	Ptype sql.NullString `json:"ptype"`
	V0    sql.NullString `json:"v0"`
	V1    sql.NullString `json:"v1"`
	V2    sql.NullString `json:"v2"`
	V3    sql.NullString `json:"v3"`
	V4    sql.NullString `json:"v4"`
	V5    sql.NullString `json:"v5"`
}

type Category struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ImageUrl    sql.NullString `json:"image_url"`
	ParentID    sql.NullString `json:"parent_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Complaint struct {
	ID         string          `json:"id"`
	ReporterID string          `json:"reporter_id"`
	TargetID   string          `json:"target_id"`
	TargetType string          `json:"target_type"`
	Reason     ComplaintReason `json:"reason"`
	Details    sql.NullString  `json:"details"`
	Status     string          `json:"status"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}

type Doctor struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Specialty     string         `json:"specialty"`
	Bio           sql.NullString `json:"bio"`
	LicenseNumber string         `json:"license_number"`
	Rating        sql.NullString `json:"rating"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Driver struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	Status        string         `json:"status"`
	VehicleTypeID sql.NullString `json:"vehicle_type_id"`
	Rating        sql.NullString `json:"rating"`
	LastLocation  interface{}    `json:"last_location"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Flight struct {
	ID             string         `json:"id"`
	AirlineName    string         `json:"airline_name"`
	FlightNumber   string         `json:"flight_number"`
	Origin         string         `json:"origin"`
	Destination    string         `json:"destination"`
	DepartureTime  time.Time      `json:"departure_time"`
	ArrivalTime    time.Time      `json:"arrival_time"`
	Price          string         `json:"price"`
	Currency       string         `json:"currency"`
	ClassType      sql.NullString `json:"class_type"`
	AvailableSeats int32          `json:"available_seats"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

type FoodItem struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	CategoryID  sql.NullString `json:"category_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Currency    string         `json:"currency"`
	ImageUrls   []string       `json:"image_urls"`
	IsAvailable sql.NullBool   `json:"is_available"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type GroceryItem struct {
	ID            string         `json:"id"`
	BusinessID    string         `json:"business_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Currency      string         `json:"currency"`
	ImageUrl      sql.NullString `json:"image_url"`
	Unit          sql.NullString `json:"unit"`
	StockQuantity int32          `json:"stock_quantity"`
	Category      sql.NullString `json:"category"`
	IsAvailable   sql.NullBool   `json:"is_available"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Hub struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Job struct {
	ID           string         `json:"id"`
	BusinessID   string         `json:"business_id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	Requirements sql.NullString `json:"requirements"`
	Category     sql.NullString `json:"category"`
	JobType      sql.NullString `json:"job_type"`
	Location     sql.NullString `json:"location"`
	SalaryRange  sql.NullString `json:"salary_range"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}

type LiquorItem struct {
	ID            string         `json:"id"`
	BusinessID    string         `json:"business_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	Price         string         `json:"price"`
	Currency      string         `json:"currency"`
	ImageUrl      sql.NullString `json:"image_url"`
	Volume        sql.NullString `json:"volume"`
	Abv           sql.NullString `json:"abv"`
	StockQuantity int32          `json:"stock_quantity"`
	Category      sql.NullString `json:"category"`
	IsAvailable   sql.NullBool   `json:"is_available"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Message struct {
	ID         string       `json:"id"`
	SenderID   string       `json:"sender_id"`
	ReceiverID string       `json:"receiver_id"`
	Content    string       `json:"content"`
	IsRead     sql.NullBool `json:"is_read"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Movie struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Synopsis        sql.NullString `json:"synopsis"`
	TrailerUrl      sql.NullString `json:"trailer_url"`
	Genre           sql.NullString `json:"genre"`
	Rating          sql.NullString `json:"rating"`
	DurationMinutes sql.NullInt32  `json:"duration_minutes"`
	PosterUrl       sql.NullString `json:"poster_url"`
	IsNowPlaying    sql.NullBool   `json:"is_now_playing"`
	Is3d            sql.NullBool   `json:"is_3d"`
	ReleaseDate     sql.NullTime   `json:"release_date"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type MovieShowtime struct {
	ID             string         `json:"id"`
	MovieID        string         `json:"movie_id"`
	BusinessID     string         `json:"business_id"`
	ShowTime       time.Time      `json:"show_time"`
	Price          string         `json:"price"`
	Currency       string         `json:"currency"`
	RoomNumber     sql.NullString `json:"room_number"`
	AvailableSeats int32          `json:"available_seats"`
}

type Notification struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	Type      sql.NullString `json:"type"`
	IsRead    sql.NullBool   `json:"is_read"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Order struct {
	ID                string         `json:"id"`
	UserID            string         `json:"user_id"`
	ParentOrderID     sql.NullString `json:"parent_order_id"`
	DriverID          sql.NullString `json:"driver_id"`
	TotalAmount       string         `json:"total_amount"`
	DeliveryFee       string         `json:"delivery_fee"`
	Currency          string         `json:"currency"`
	Status            string         `json:"status"`
	ShippingAddressID sql.NullString `json:"shipping_address_id"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type OrderItem struct {
	ID         string       `json:"id"`
	OrderID    string       `json:"order_id"`
	BusinessID string       `json:"business_id"`
	ItemID     string       `json:"item_id"`
	ItemType   string       `json:"item_type"`
	Quantity   int32        `json:"quantity"`
	UnitPrice  string       `json:"unit_price"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type PharmacyItem struct {
	ID                   string         `json:"id"`
	BusinessID           string         `json:"business_id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Price                string         `json:"price"`
	Currency             string         `json:"currency"`
	ImageUrl             sql.NullString `json:"image_url"`
	RequiresPrescription sql.NullBool   `json:"requires_prescription"`
	StockQuantity        int32          `json:"stock_quantity"`
	Category             sql.NullString `json:"category"`
	IsAvailable          sql.NullBool   `json:"is_available"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type Product struct {
	ID                 string         `json:"id"`
	BusinessID         string         `json:"business_id"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	Price              string         `json:"price"`
	Currency           string         `json:"currency"`
	StockQuantity      int32          `json:"stock_quantity"`
	CategoryID         sql.NullString `json:"category_id"`
	BrandID            sql.NullString `json:"brand_id"`
	ModelID            sql.NullString `json:"model_id"`
	ImageUrls          []string       `json:"image_urls"`
	Rating             sql.NullString `json:"rating"`
	ReviewCount        sql.NullInt32  `json:"review_count"`
	IsFeatured         sql.NullBool   `json:"is_featured"`
	IsFlashSale        sql.NullBool   `json:"is_flash_sale"`
	DiscountPercentage sql.NullString `json:"discount_percentage"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
}

type ProductDiscount struct {
	ID            string       `json:"id"`
	ProductID     string       `json:"product_id"`
	DiscountType  string       `json:"discount_type"`
	DiscountValue string       `json:"discount_value"`
	StartAt       sql.NullTime `json:"start_at"`
	EndAt         sql.NullTime `json:"end_at"`
	CreatedAt     sql.NullTime `json:"created_at"`
	UpdatedAt     sql.NullTime `json:"updated_at"`
}

type ProductModel struct {
	ID        string         `json:"id"`
	BrandID   string         `json:"brand_id"`
	Name      string         `json:"name"`
	ImageUrl  sql.NullString `json:"image_url"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type ProductVariant struct {
	ID            string                `json:"id"`
	ProductID     string                `json:"product_id"`
	Sku           sql.NullString        `json:"sku"`
	Price         string                `json:"price"`
	StockQuantity int32                 `json:"stock_quantity"`
	Attributes    pqtype.NullRawMessage `json:"attributes"`
	CreatedAt     sql.NullTime          `json:"created_at"`
	UpdatedAt     sql.NullTime          `json:"updated_at"`
}

type Property struct {
	ID               string           `json:"id"`
	BusinessID       string           `json:"business_id"`
	Title            string           `json:"title"`
	Description      sql.NullString   `json:"description"`
	AddressID        sql.NullString   `json:"address_id"`
	PricePerNight    string           `json:"price_per_night"`
	Currency         string           `json:"currency"`
	NumberOfGuests   sql.NullInt32    `json:"number_of_guests"`
	NumberOfBedrooms sql.NullInt32    `json:"number_of_bedrooms"`
	Type             PropertyTypeEnum `json:"type"`
	ImageUrls        []string         `json:"image_urls"`
	CreatedAt        sql.NullTime     `json:"created_at"`
	UpdatedAt        sql.NullTime     `json:"updated_at"`
}

type PropertyBooking struct {
	ID           string       `json:"id"`
	UserID       string       `json:"user_id"`
	PropertyID   string       `json:"property_id"`
	CheckInDate  time.Time    `json:"check_in_date"`
	CheckOutDate time.Time    `json:"check_out_date"`
	TotalAmount  string       `json:"total_amount"`
	Currency     string       `json:"currency"`
	Status       string       `json:"status"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Refreshment struct {
	ID         string       `json:"id"`
	BusinessID string       `json:"business_id"`
	Name       string       `json:"name"`
	Price      string       `json:"price"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Review struct {
	ID         string         `json:"id"`
	TargetID   string         `json:"target_id"`
	TargetType string         `json:"target_type"`
	UserID     string         `json:"user_id"`
	Rating     int32          `json:"rating"`
	Comment    sql.NullString `json:"comment"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Rfq struct {
	ID          string         `json:"id"`
	BuyerID     string         `json:"buyer_id"`
	BusinessID  string         `json:"business_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RfqItem struct {
	ID          string         `json:"id"`
	RfqID       string         `json:"rfq_id"`
	ProductID   sql.NullString `json:"product_id"`
	ItemName    string         `json:"item_name"`
	Quantity    int32          `json:"quantity"`
	Unit        sql.NullString `json:"unit"`
	TargetPrice sql.NullString `json:"target_price"`
}

type Service struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	ServiceType string         `json:"service_type"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BasePrice   string         `json:"base_price"`
	Currency    string         `json:"currency"`
	Location    interface{}    `json:"location"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ServiceBooking struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	ServiceType   string         `json:"service_type"`
	ServiceItemID string         `json:"service_item_id"`
	ProviderID    sql.NullString `json:"provider_id"`
	ProviderType  sql.NullString `json:"provider_type"`
	StartTime     time.Time      `json:"start_time"`
	EndTime       sql.NullTime   `json:"end_time"`
	TotalAmount   string         `json:"total_amount"`
	Currency      string         `json:"currency"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type Task struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Priority int32  `json:"priority"`
}

type TaxiTrip struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	DriverID        sql.NullString `json:"driver_id"`
	PickupLocation  interface{}    `json:"pickup_location"`
	DropoffLocation interface{}    `json:"dropoff_location"`
	TotalAmount     string         `json:"total_amount"`
	Currency        string         `json:"currency"`
	Status          string         `json:"status"`
	AcceptedAt      sql.NullTime   `json:"accepted_at"`
	StartedAt       sql.NullTime   `json:"started_at"`
	CompletedAt     sql.NullTime   `json:"completed_at"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type Ticket struct {
	ID             string       `json:"id"`
	UserID         string       `json:"user_id"`
	ShowtimeID     string       `json:"showtime_id"`
	SeatNumber     string       `json:"seat_number"`
	TicketNumber   string       `json:"ticket_number"`
	QrCodeData     string       `json:"qr_code_data"`
	RefreshmentIds []string     `json:"refreshment_ids"`
	TotalAmount    string       `json:"total_amount"`
	Status         string       `json:"status"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type Tour struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Location    sql.NullString `json:"location"`
	Price       string         `json:"price"`
	Currency    string         `json:"currency"`
	Rating      sql.NullString `json:"rating"`
	ImageUrl    sql.NullString `json:"image_url"`
	Duration    sql.NullString `json:"duration"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Transaction struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	OrderID   sql.NullString `json:"order_id"`
	Amount    string         `json:"amount"`
	Currency  string         `json:"currency"`
	Status    string         `json:"status"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID                string         `json:"id"`
	Email             string         `json:"email"`
	PasswordHash      string         `json:"password_hash"`
	FirstName         string         `json:"first_name"`
	LastName          sql.NullString `json:"last_name"`
	DateOfBirth       sql.NullTime   `json:"date_of_birth"`
	PhoneNumber       sql.NullString `json:"phone_number"`
	ProfilePictureUrl sql.NullString `json:"profile_picture_url"`
	IsBlacklisted     sql.NullBool   `json:"is_blacklisted"`
	StatusNotes       sql.NullString `json:"status_notes"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID string       `json:"user_id"`
	Role   UserRoleType `json:"role"`
}

type UserWallet struct {
	UserID      string       `json:"user_id"`
	Balance     string       `json:"balance"`
	LastUpdated sql.NullTime `json:"last_updated"`
}

type VehicleType struct {
	ID                string       `json:"id"`
	Name              string       `json:"name"`
	PassengerCapacity int32        `json:"passenger_capacity"`
	BasePricePerKm    string       `json:"base_price_per_km"`
	InitialFee        string       `json:"initial_fee"`
	Currency          string       `json:"currency"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}

type VendorDocument struct {
	ID          string         `json:"id"`
	BusinessID  string         `json:"business_id"`
	Type        DocumentType   `json:"type"`
	Url         string         `json:"url"`
	Status      string         `json:"status"`
	ReviewNotes sql.NullString `json:"review_notes"`
	VerifiedAt  sql.NullTime   `json:"verified_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type WholesaleItem struct {
	ID           string         `json:"id"`
	BusinessID   string         `json:"business_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	ImageUrls    []string       `json:"image_urls"`
	UnitPrice    sql.NullString `json:"unit_price"`
	BulkPrice    sql.NullString `json:"bulk_price"`
	BulkQuantity sql.NullInt32  `json:"bulk_quantity"`
	Category     sql.NullString `json:"category"`
	IsAvailable  sql.NullBool   `json:"is_available"`
	Rating       sql.NullString `json:"rating"`
	ReviewCount  sql.NullInt32  `json:"review_count"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
