// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Business Locations
	AddBusinessLocation(ctx context.Context, arg AddBusinessLocationParams) error
	AddItemToCart(ctx context.Context, arg AddItemToCartParams) (CartItem, error)
	AddRFQItem(ctx context.Context, arg AddRFQItemParams) (RfqItem, error)
	// Reviews
	AddReview(ctx context.Context, arg AddReviewParams) (Review, error)
	AssignDriverToOrder(ctx context.Context, arg AssignDriverToOrderParams) (Order, error)
	// Role management
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) (UserRole, error)
	ClearCart(ctx context.Context, userID string) error
	CountSellerListings(ctx context.Context, sellerID string) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	// B2B Quotes
	CreateB2BQuote(ctx context.Context, arg CreateB2BQuoteParams) (B2bQuote, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateBusRoute(ctx context.Context, arg CreateBusRouteParams) (BusRoute, error)
	CreateBusTicket(ctx context.Context, arg CreateBusTicketParams) (Ticket, error)
	// Business
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateC2CListing(ctx context.Context, arg CreateC2CListingParams) (C2cListing, error)
	// C2C Marketplace
	CreateC2CSeller(ctx context.Context, arg CreateC2CSellerParams) (C2cSeller, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Health
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreateFlightTicket(ctx context.Context, arg CreateFlightTicketParams) (Ticket, error)
	CreateFoodItem(ctx context.Context, arg CreateFoodItemParams) (FoodItem, error)
	CreateGroceryItem(ctx context.Context, arg CreateGroceryItemParams) (GroceryItem, error)
	// Hubs
	CreateHub(ctx context.Context, arg CreateHubParams) (Hub, error)
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	// Orders
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePharmacyItem(ctx context.Context, arg CreatePharmacyItemParams) (PharmacyItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductModel(ctx context.Context, arg CreateProductModelParams) (ProductModel, error)
	CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error)
	CreatePropertyBooking(ctx context.Context, arg CreatePropertyBookingParams) (PropertyBooking, error)
	// B2B / RFQs
	CreateRFQ(ctx context.Context, arg CreateRFQParams) (Rfq, error)
	// Services
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	// Service Bookings
	CreateServiceBooking(ctx context.Context, arg CreateServiceBookingParams) (ServiceBooking, error)
	CreateTaxiTrip(ctx context.Context, arg CreateTaxiTripParams) (TaxiTrip, error)
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Wholesale Items
	CreateWholesaleItem(ctx context.Context, arg CreateWholesaleItemParams) (WholesaleItem, error)
	DeleteBrand(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	// Delete Product
	DeleteProduct(ctx context.Context, id string) error
	DeleteProductModel(ctx context.Context, id string) error
	GetB2BDashboardStats(ctx context.Context, buyerID string) (GetB2BDashboardStatsRow, error)
	GetBrands(ctx context.Context) ([]GetBrandsRow, error)
	GetBusinessByID(ctx context.Context, id string) (Business, error)
	GetBusinessesByOwnerID(ctx context.Context, ownerID string) ([]Business, error)
	GetC2CListingByID(ctx context.Context, id string) (C2cListing, error)
	GetC2CSellerByUserID(ctx context.Context, userID string) (C2cSeller, error)
	// Cart Items
	GetCartItemsByUserID(ctx context.Context, userID string) ([]GetCartItemsByUserIDRow, error)
	GetCategories(ctx context.Context) ([]Category, error)
	GetFeaturedProducts(ctx context.Context, arg GetFeaturedProductsParams) ([]Product, error)
	GetFoodItemByID(ctx context.Context, id string) (GetFoodItemByIDRow, error)
	GetMovieDetails(ctx context.Context, id string) (Movie, error)
	GetNearbyDrivers(ctx context.Context, arg GetNearbyDriversParams) ([]GetNearbyDriversRow, error)
	GetNearbyMotorbikeDrivers(ctx context.Context, arg GetNearbyMotorbikeDriversParams) ([]GetNearbyMotorbikeDriversRow, error)
	GetOrdersByUserID(ctx context.Context, userID string) ([]Order, error)
	GetProductByIDWithDetails(ctx context.Context, id string) (GetProductByIDWithDetailsRow, error)
	// Products (Ecommerce)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]GetProductsRow, error)
	GetProductsByBusiness(ctx context.Context, arg GetProductsByBusinessParams) ([]GetProductsByBusinessRow, error)
	GetPropertyByID(ctx context.Context, id string) (GetPropertyByIDRow, error)
	GetQuotesForRFQ(ctx context.Context, rfqID string) ([]GetQuotesForRFQRow, error)
	GetRFQWithItems(ctx context.Context, id string) ([]GetRFQWithItemsRow, error)
	GetReviewsByTarget(ctx context.Context, arg GetReviewsByTargetParams) ([]Review, error)
	GetServiceBookingsByUserID(ctx context.Context, userID string) ([]ServiceBooking, error)
	GetServiceByID(ctx context.Context, id string) (Service, error)
	// Users
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Wallet & Transactions
	GetWalletBalance(ctx context.Context, userID string) (UserWallet, error)
	GetWholesaleItemByID(ctx context.Context, id string) (GetWholesaleItemByIDRow, error)
	// Jobs
	ListActiveJobs(ctx context.Context) ([]ListActiveJobsRow, error)
	// Food
	ListAllFoodItems(ctx context.Context) ([]ListAllFoodItemsRow, error)
	ListAppointmentsByPatient(ctx context.Context, patientID string) ([]ListAppointmentsByPatientRow, error)
	ListBrandsByCategory(ctx context.Context, categoryID sql.NullString) ([]Brand, error)
	// Travel
	ListBusRoutes(ctx context.Context, arg ListBusRoutesParams) ([]ListBusRoutesRow, error)
	ListBusinessLocations(ctx context.Context, businessID string) ([]Address, error)
	ListBusinessesByType(ctx context.Context, miniserviceType string) ([]Business, error)
	ListC2CListings(ctx context.Context) ([]ListC2CListingsRow, error)
	ListComingSoonMovies(ctx context.Context) ([]Movie, error)
	ListDoctors(ctx context.Context) ([]ListDoctorsRow, error)
	// Flights
	ListFlights(ctx context.Context) ([]Flight, error)
	ListFoodItemsByCategory(ctx context.Context, name string) ([]ListFoodItemsByCategoryRow, error)
	// Grocery
	ListGroceryItems(ctx context.Context) ([]ListGroceryItemsRow, error)
	ListGroceryItemsByBusiness(ctx context.Context, businessID string) ([]GroceryItem, error)
	// Liquor
	ListLiquorItems(ctx context.Context) ([]ListLiquorItemsRow, error)
	ListLiquorItemsByBusiness(ctx context.Context, businessID string) ([]LiquorItem, error)
	ListModelsByBrand(ctx context.Context, brandID string) ([]ProductModel, error)
	ListMovieShowtimes(ctx context.Context, movieID string) ([]ListMovieShowtimesRow, error)
	// Cinema
	ListNowPlayingMovies(ctx context.Context) ([]Movie, error)
	// Pharmacy Items (Already exists, ensures prescription check is respected for OTC)
	ListPharmacyItems(ctx context.Context) ([]PharmacyItem, error)
	ListPharmacyItemsByBusiness(ctx context.Context, businessID string) ([]PharmacyItem, error)
	ListProductModels(ctx context.Context) ([]ListProductModelsRow, error)
	// Property
	ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error)
	ListRFQsForBusiness(ctx context.Context, businessID string) ([]ListRFQsForBusinessRow, error)
	ListRFQsForBuyer(ctx context.Context, buyerID string) ([]ListRFQsForBuyerRow, error)
	ListRefreshmentsByCinema(ctx context.Context, businessID string) ([]Refreshment, error)
	ListServicesByType(ctx context.Context, serviceType string) ([]ListServicesByTypeRow, error)
	// Travel/Tours
	ListTours(ctx context.Context) ([]ListToursRow, error)
	// Addresses
	ListUserAddresses(ctx context.Context, userID string) ([]Address, error)
	// Bills
	ListUserBills(ctx context.Context, userID string) ([]Bill, error)
	// messaging & notifications
	ListUserMessages(ctx context.Context, senderID string) ([]Message, error)
	ListUserNotifications(ctx context.Context, userID string) ([]Notification, error)
	ListWholesaleItems(ctx context.Context) ([]ListWholesaleItemsRow, error)
	ListWholesaleItemsByBusiness(ctx context.Context, businessID string) ([]WholesaleItem, error)
	LockAndDecrementStock(ctx context.Context, arg LockAndDecrementStockParams) error
	RemoveCartItem(ctx context.Context, id string) error
	SearchPropertiesByLocation(ctx context.Context, arg SearchPropertiesByLocationParams) ([]Property, error)
	SearchStoresByLocation(ctx context.Context, arg SearchStoresByLocationParams) ([]SearchStoresByLocationRow, error)
	UpdateB2BQuoteStatus(ctx context.Context, arg UpdateB2BQuoteStatusParams) (B2bQuote, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error)
	// Business Status
	UpdateBusinessStatus(ctx context.Context, arg UpdateBusinessStatusParams) (Business, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	// Taxi
	UpdateDriverLocation(ctx context.Context, arg UpdateDriverLocationParams) (Driver, error)
	UpdateDriverStatus(ctx context.Context, arg UpdateDriverStatusParams) (Driver, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductModel(ctx context.Context, arg UpdateProductModelParams) (ProductModel, error)
	UpdateRFQStatus(ctx context.Context, arg UpdateRFQStatusParams) (Rfq, error)
	UpdateServiceBookingStatus(ctx context.Context, arg UpdateServiceBookingStatusParams) (ServiceBooking, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (UserWallet, error)
}

var _ Querier = (*Queries)(nil)
